import type { Model, Profile } from "@hermetika/shared";

// live pantheon — exactly what's resident on the two owned DGX Sparks (verified).
// lanes: gpu://spark = spark-1 (hot) · gpu://sparktail = spark-2 (breadth, failover twin).
// each Spark serves Ollama behind a bearer-auth Caddy over Tailscale.
export const MODELS: Model[] = [
  {
    id: "m_hermes_trismegistus",
    slug: "hermes-trismegistus",
    name: "Hermes Trismegistus",
    kind: "esoteric",
    lineage: null, // dynasty root — the patron model of the pantheon
    backend: "gpu",
    backendRef: "gpu://spark/hermes-trismegistus",
    speed: "standard",
    hfId: "teknium/Hermes-Trismegistus-Mistral-7B",
    license: "apache-2.0",
    params: "7B",
    releasedAt: "2023-10-01",
    cardMd:
      "# Hermes Trismegistus\nTeknium's occult expert — the first open LLM devoted to the esoteric, occult, alchemy, tarot, and hermeticism. Namesake of the pantheon. spark-1.",
    tags: ["esoteric", "occult", "hermes", "teknium"],
    enabled: true,
  },
  {
    id: "m_hermes3_mini",
    slug: "hermes-3-mini",
    name: "Hermes 3 (3B)",
    kind: "tech",
    lineage: "hermes-trismegistus",
    backend: "gpu",
    backendRef: "gpu://spark/hermes-3-mini",
    speed: "fast",
    hfId: "NousResearch/Hermes-3-Llama-3.2-3B",
    license: "llama3",
    params: "3B",
    releasedAt: "2024-09-01",
    cardMd:
      "# Hermes 3 (3B)\nNous Hermes 3 full-finetune of Llama-3.2-3B — steerable, function-calling, roleplay. The dynasty's fast heir. spark-1.",
    tags: ["hermes", "nous", "function-calling"],
    enabled: true,
  },
  {
    id: "m_abliterate_mini",
    slug: "abliterate-mini",
    name: "Abliterate Mini",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://spark/abliterate-mini",
    speed: "fast",
    hfId: "huihui_ai/qwen2.5-abliterate:0.5b",
    license: "apache-2.0",
    params: "0.5B",
    releasedAt: "2024-11-01",
    cardMd:
      "# Abliterate Mini\nRefusal-ablated Qwen2.5-0.5B — tiny, uncensored. Corporate APIs won't serve it, so we own the weights. spark-1.",
    tags: ["uncensored", "abliterated", "tiny"],
    enabled: true,
  },
  {
    id: "m_trismegistus_og",
    slug: "trismegistus-og",
    name: "Trismegistus (OG)",
    kind: "esoteric",
    lineage: "hermes-trismegistus",
    backend: "gpu",
    backendRef: "gpu://sparktail/trismegistus-og",
    speed: "standard",
    hfId: "teknium/Mistral-Trismegistus-7B",
    license: "apache-2.0",
    params: "7B",
    releasedAt: "2023-09-01",
    cardMd:
      "# Trismegistus (OG)\nThe original occult-expert Mistral finetune, ancestor of Hermes Trismegistus. Kept for the dynasty lineage. spark-2.",
    tags: ["esoteric", "occult", "teknium", "lineage"],
    enabled: true,
  },
  {
    id: "m_abliterate_3b",
    slug: "abliterate-3b",
    name: "Abliterate 3B",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/abliterate-3b",
    speed: "fast",
    hfId: "huihui_ai/qwen2.5-abliterate:3b",
    license: "apache-2.0",
    params: "3B",
    releasedAt: "2024-11-01",
    cardMd:
      "# Abliterate 3B\nRefusal-ablated Qwen2.5-3B — the larger uncensored sibling. spark-2.",
    tags: ["uncensored", "abliterated"],
    enabled: true,
  },
  {
    id: "m_tinystories",
    slug: "tinystories",
    name: "TinyStories",
    kind: "story",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/tinystories",
    speed: "fast",
    hfId: "tensorblock/tinyllama-15M-stories-GGUF",
    license: "mit",
    params: "15M",
    releasedAt: "2023-05-01",
    cardMd:
      "# TinyStories\nA 15M-param TinyLlama that writes coherent simple stories — proof small can be magical. spark-2.",
    tags: ["story", "tiny", "showpiece"],
    enabled: true,
  },
  {
    id: "m_ascii_artist",
    slug: "ascii-artist",
    name: "ASCII Artist",
    kind: "ascii",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/ascii-artist",
    speed: "standard",
    hfId: "nonetrix/llama-3-8b-ascii-art-gen",
    license: "apache-2.0",
    params: "8B",
    releasedAt: "2024-04-01",
    cardMd:
      "# ASCII Artist\nLlama-3-8B finetuned to draw with characters. System prompt: 'Make ASCII art of X'. spark-2.",
    tags: ["ascii", "art", "generative"],
    enabled: true,
  },

  // ── esoteric batch (spark-1) ──
  {
    id: "m_tarot_tinyllama",
    slug: "tarot-tinyllama",
    name: "Tarot (TinyLlama)",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://spark/tarot-tinyllama",
    speed: "fast",
    hfId: "mradermacher/TinyLlama-1.1B-Tarot-Chat-v1.0-GGUF",
    license: "unknown",
    params: "1.1B",
    releasedAt: "2024-03-01",
    cardMd: "# Tarot (TinyLlama)\nTinyLlama tuned for tarot-reading chat. spark-1.",
    tags: ["esoteric", "tarot", "divination"],
    enabled: true,
  },
  {
    id: "m_tarot_qwen",
    slug: "tarot-qwen",
    name: "Tarot (Qwen 7B)",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://spark/tarot-qwen",
    speed: "standard",
    hfId: "mradermacher/tarot-qwen2.5-7b-GGUF",
    license: "unknown",
    params: "7B",
    releasedAt: "2024-12-01",
    cardMd: "# Tarot (Qwen 7B)\nQwen2.5-7B tuned for richer tarot readings. spark-1.",
    tags: ["esoteric", "tarot", "divination"],
    enabled: true,
  },
  {
    id: "m_oracle",
    slug: "oracle",
    name: "Oracle",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://spark/oracle",
    speed: "fast",
    hfId: "mradermacher/Oracle-Tinyllama-GGUF",
    license: "unknown",
    params: "1.1B",
    releasedAt: "2024-03-01",
    cardMd: "# Oracle\nTinyLlama oracle/divination responder. spark-1.",
    tags: ["esoteric", "oracle", "divination"],
    enabled: true,
  },
  {
    id: "m_esoteric_sage",
    slug: "esoteric-sage",
    name: "Esoteric Sage",
    kind: "esoteric",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://spark/esoteric-sage",
    speed: "standard",
    hfId: "mradermacher/EsotericSage-12B-GGUF",
    license: "unknown",
    params: "12B",
    releasedAt: "2025-01-01",
    cardMd: "# Esoteric Sage\n12B esoteric/occult-knowledge conversational model. spark-1.",
    tags: ["esoteric", "occult", "knowledge"],
    enabled: true,
  },

  // ── ascii + curios + creative batch (spark-2) ──
  {
    id: "m_ascii_cats",
    slug: "ascii-cats",
    name: "ASCII Cats",
    kind: "ascii",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/ascii-cats",
    speed: "fast",
    hfId: "omosaad/Llama-3.2-3B-ascii-cats-lora-q4_k_m-GGUF",
    license: "apache-2.0",
    params: "3B",
    releasedAt: "2024-10-01",
    cardMd: "# ASCII Cats\nLlama-3.2-3B that draws ASCII cats. spark-2.",
    tags: ["ascii", "art", "cats"],
    enabled: true,
  },
  {
    id: "m_ascii_quietstar",
    slug: "ascii-quietstar",
    name: "ASCII Quiet-Star",
    kind: "ascii",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/ascii-quietstar",
    speed: "standard",
    hfId: "liminerity/Mistral-quiet-star-ascii-demo-gguf",
    license: "apache-2.0",
    params: "7B",
    releasedAt: "2024-05-01",
    cardMd: "# ASCII Quiet-Star\nMistral-7B quiet-star ASCII demo. spark-2.",
    tags: ["ascii", "art", "experimental"],
    enabled: true,
  },
  {
    id: "m_gemma_chess",
    slug: "gemma-chess",
    name: "Gemma Chess",
    kind: "puzzle",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/gemma-chess",
    speed: "fast",
    hfId: "mradermacher/Gemma3-Chess-270m-GGUF",
    license: "gemma",
    params: "270M",
    releasedAt: "2025-04-01",
    cardMd: "# Gemma Chess\nTiny Gemma3 that plays/continues chess games. spark-2.",
    tags: ["puzzle", "chess", "game"],
    enabled: true,
  },
  {
    id: "m_maze",
    slug: "maze",
    name: "Maze",
    kind: "puzzle",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/maze",
    speed: "fast",
    hfId: "mradermacher/maze-0.6b-GGUF",
    license: "apache-2.0",
    params: "0.6B",
    releasedAt: "2025-02-01",
    cardMd: "# Maze\nQwen3-0.6B maze/spatial generation. spark-2.",
    tags: ["puzzle", "maze", "spatial"],
    enabled: true,
  },
  {
    id: "m_haiku",
    slug: "haiku",
    name: "Haiku",
    kind: "wordplay",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/haiku",
    speed: "fast",
    hfId: "mradermacher/deep-haiku-gpt-2-GGUF",
    license: "mit",
    params: "0.1B",
    releasedAt: "2022-08-01",
    cardMd: "# Haiku\nGPT-2 that writes haiku from keyword prompts. spark-2. (completion-style)",
    tags: ["wordplay", "poetry", "haiku"],
    enabled: true,
  },
  {
    id: "m_adventure",
    slug: "adventure",
    name: "Adventure",
    kind: "story",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/adventure",
    speed: "fast",
    hfId: "mradermacher/Pythia-160M-Deduped-Adventure-GGUF",
    license: "unknown",
    params: "160M",
    releasedAt: "2023-07-01",
    cardMd: "# Adventure\nTiny Pythia AI-Dungeon-style text adventure. spark-2. (completion-style)",
    tags: ["story", "text-adventure", "interactive-fiction"],
    enabled: true,
  },
  {
    id: "m_carnice_27b",
    slug: "carnice-27b",
    name: "Carnice 27B",
    kind: "tech",
    lineage: null,
    backend: "gpu",
    backendRef: "gpu://sparktail/carnice-27b",
    speed: "standard",
    hfId: "kai-os/Carnice-27b-GGUF",
    license: "apache-2.0",
    params: "27B",
    releasedAt: "2025-05-01",
    cardMd: "# Carnice 27B\nQwen3.5-27B Hermes-agent-style model — the pantheon's heavyweight. spark-2.",
    tags: ["creative", "flagship", "hermes-agent"],
    enabled: true,
  },
];

// operator — one custom Hermes profile runs the pantheon (curate, watch, swap, notify).
export const PROFILES: Profile[] = [
  {
    id: "p_hermetika",
    slug: "hermes.hermetika",
    name: "Hermetika",
    peerId: "hermetika",
    role: "orchestrator",
    curates: MODELS.map((m) => m.slug),
  },
];
